# Generated by Django 6.0.4 on 2026-06-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name='Phone Number'),
        ),
    ]
