# Generated by Django 6.0.4 on 2026-05-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('c', 'Custumer'), ('s', 'Shopkeeper')], default='c', max_length=1, verbose_name='Role'),
        ),
    ]
