# Generated by Django 6.0.4 on 2026-05-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
    ]
